function fh= SM_Instructions_UI(CONST, instr)

global USER_DATA;

%screen_Size = get(0,'ScreenSize');
win_Size = SM_GetScreenSize;
fh = figure('Visible','on','Name','Instructions',...
    'MenuBar','none',...
    'Toolbar','none', ...
    'Color',[0.8 0.8 0.8],...
    'Position',win_Size);

% Display instructions
display_String = sprintf('%s','Instructions for this run:');
uicontrol(fh,'Style','text',...
    'Visible','on',...
    'String',display_String,...
    'Min',1,'Max',3,...
    'FontSize',18, ...
    'BackgroundColor',[0.8 0.8 0.8], ...
    'HorizontalAlignment','left',...
    'Units','Normalized',...
    'Position',[0.2 0.7 0.8 0.1]);
%'Position',[(screen_Size(3)/6) (screen_Size(4)/1.5)+60 800 35]);

for k = 1:length(instr)
    uicontrol(fh,'Style','text',...
        'Visible','on',...
        'String',instr{k},...
        'Min',1,'Max',45,...
        'FontSize',16, ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'HorizontalAlignment','left',...
        'Units','Normalized',...
        'Position',[0.3 0.6-0.05*(k-1) 0.6 0.03]);
    %'Position',[(screen_Size(3)/2)-350 (screen_Size(4)/1.5)-30*(k-1) 500 30]);
end

proceed_Button_Ctl = uicontrol(fh,'Style','pushbutton',...
    'String','PROCEED',...
    'Visible','on',...
    'Units','Normalized',...
    'Position',[0.85 0.1 0.13 0.04]);
%'Position',[(screen_Size(3))-150 120 140 30]);
set(proceed_Button_Ctl,'Callback',{@user_Proceed} );
set(fh,'KeyPressFcn',{@user_Proceed});

% Quit
quit_Ctl = uicontrol(fh,'Style','pushbutton','String','SKIP',...
    'Visible','on',...
    'Units','Normalized',...
    'Position',[0.85 0.05 0.13 0.04]);
%'Position',[(screen_Size(3))-150 75 140 30]);
set(quit_Ctl,'Callback',{@user_Exit} );


end



function user_Proceed(hObj,event)

global USER_DATA

USER_DATA.action = 'PROCEED';
uiresume;

end



function user_Exit(hObj,event)

global USER_DATA

USER_DATA.action = 'QUIT';
uiresume;

end


